set(HDF5_EXTRA_ARGS  
	-DHDF5_ENABLE_THREADSAFE=Off
	-DHDF5_BUILD_CPP_LIB=Off
	-DBUILD_TESTING=Off
	-DHDF5_BUILD_TOOLS=Off
	-DHDF5_BUILD_EXAMPLES=Off
	-DHDF5_BUILD_HL_LIB=On
	-DBUILD_STATIC_CRT_LIBS=On
	-DBUILD_SHARED_LIBS=On
)

ExternalProject_Add(external_hdf5
  URL ${HDF5_URI}
  DOWNLOAD_DIR ${CMAKE_CURRENT_SOURCE_DIR}/Downloads
  URL_HASH MD5=${HDF5_HASH}
  PREFIX ${CMAKE_CURRENT_BINARY_DIR}/build/hdf5
  PATCH_COMMAND ${PATCH_CMD} --verbose -p 0 -d ${CMAKE_CURRENT_BINARY_DIR}/build/hdf5/src/external_hdf5 < ${CMAKE_CURRENT_SOURCE_DIR}/Diffs/hdf5.diff 
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${LIBDIR}/hdf5 ${HDF5_EXTRA_ARGS}
  INSTALL_DIR ${LIBDIR}/hdf5
)
