set(LLVM_EXTRA_ARGS 
 -DLLVM_USE_CRT_RELEASE=MT 
 -DLLVM_USE_CRT_DEBUG=MTd
 -DLLVM_INCLUDE_TESTS=OFF 
 -DLLVM_TARGETS_TO_BUILD=X86
 -DLLVM_INCLUDE_EXAMPLES=OFF
 -DLLVM_ENABLE_TERMINFO=OFF
   )

#short project name due to long filename issues on windows 
ExternalProject_Add(ll
  URL ${LLVM_URI}
  DOWNLOAD_DIR ${CMAKE_CURRENT_SOURCE_DIR}/Downloads
  URL_HASH MD5=${LLVM_HASH}
  CMAKE_GENERATOR "NMake Makefiles"
  PREFIX ${CMAKE_CURRENT_BINARY_DIR}/build/ll
  PATCH_COMMAND ${PATCH_CMD} -p 0 -d ${CMAKE_CURRENT_BINARY_DIR}/build/ll/src/ll < ${CMAKE_CURRENT_SOURCE_DIR}/Diffs/llvm-alloca-fix.patch.patch
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${LIBDIR}/llvm ${DEFAULT_CMAKE_FLAGS} ${LLVM_EXTRA_ARGS}
  INSTALL_DIR ${LIBDIR}/llvm
)
